# Generated by Django 5.2.4 on 2025-11-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste2', models.CharField(max_length=100, verbose_name='teste2')),
                ('teste3', models.IntegerField(verbose_name='teste3')),
            ],
        ),
    ]
